version: '3'

services:
  api:
    build: item-inventory-backend
    depends_on:
      - item_inventory
    ports:
      - "8081:8081"
  item_inventory:
    image: postgres:latest
    environment:
      - DATABASE_HOST=item_inventory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5433:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
     # - /Users/j.j./Desktop/DockerData:/var/lib/postgresql/data